### ISSUE TITLE
docker启动问题

### ISSUE THREAD

**Issue by m1911** [jiangwenyuan/docker-nuster#2]
为什么用你的镜像启动就退出，启动不成功呢
78638755d730        nuster/nuster       "/docker-entrypoint.…"   5 seconds ago       Exited (127) 4 seconds ago                        agitated_bartik
b03e78baac14        nuster/nuster       "/docker-entrypoint.…"   25 minutes ago      Exited (127) 25 minutes ago                       gracious_nobel
56a42d781843        nuster/nuster       "/docker-entrypoint.…"   30 minutes ago      Exited (127) 30 minutes ago                       amazing_darwin
3c35b12c2860        nuster/nuster       "/docker-entrypoint.…"   30 minutes ago      Exited (127) 30 minutes ago                       infallible_perlman
e93025116aea        nuster/nuster       "/docker-entrypoint.…"   32 minutes ago      Exited (127) 32 minutes ago                       nuster

**Comment by jiangwenyuan** [comment]
@m1911 请问用的是最新版本吗？v1.7.10.1开始配置文件中某些参数不兼容之前的版本。

**Comment by m1911** [comment]
@jiangwenyuan 你这个docker 镜像不是直接启动吗？
我看https://github.com/jiangwenyuan/docker-nuster  这上面的步骤是创建直接的镜像用的啊

**Comment by jiangwenyuan** [comment]
@m1911 需要创建一个基本配置文件，比如/path/to/nuster.cfg

内容大概类似

```
global
    nuster cache on data-size 100m
frontend web1
    bind *:8080
    mode http
    default_backend app1
backend app1
    balance roundrobin
    mode http
    nuster cache
    nuster rule all

    server s1 10.0.0.10:8080
    server s2 10.0.0.11:8080
```

server部分用自己的后端服务器替换，然后

`docker run -d -p 8080:8080 -v /path/to/nuster.cfg:/etc/nuster/nuster.cfg:ro nuster/nuster`

**Comment by m1911** [comment]
@jiangwenyuan nuster.cfg 这个文件必须要创建在本机是吧？ 这个配置文件可以全部参考HAProxy？

**Comment by jiangwenyuan** [comment]
@m1911 是的，也可以copy到Dockerfile里，这样就不需要mount，配置文件和HAProxy一样，不过添加了几个nuster用的指令。指令可以参考https://github.com/jiangwenyuan/nuster#directives
例子可以参考https://github.com/jiangwenyuan/nuster#example

**Comment by m1911** [comment]
@jiangwenyuan 如果需要修改下配置文件 直接修改本地的就可以了？ 然后在重新下docker？

**Comment by jiangwenyuan** [comment]
@m1911 对，需要重启

**Comment by m1911** [comment]
@jiangwenyuan 好的，了解了 一会在继续测试下

**Comment by m1911** [comment]
docker run -d -p 8080:8080 -v /home/conf/nuster.cfg:/etc/nuster/nuster.cfg:ro nuster/nuster
用这个命令来启动还是直接退出了
@jiangwenyuan

**Comment by jiangwenyuan** [comment]
@m1911 发现是haproxy 1.8删除了 haproxy-systemd-wrapper，已经修复，请docker pull最新版，麻烦再试一下

**Comment by m1911** [comment]
@jiangwenyuan 我看见你更新了docker 文件了我稍后测试下
