### ISSUE TITLE
use CMD ["nuster", "-f", "/etc/nuster"]

### ISSUE THREAD

**Issue by everyx** [jiangwenyuan/docker-nuster#5]
Hi, can we load config directory for default, so that we can work out of box with s single config file or multiple config files.

Just change `CMD ["nuster", "-f", "/etc/nuster/nuster.cfg"]` to `CMD ["nuster", "-f", "/etc/nuster"]`

**Comment by jiangwenyuan** [comment]
Not only config files but also other files like errors are stored in /etc/nuster. 

You could do it it command line though
